/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.gradlex.extra-java-module-info") version "1.8"
    id("com.gradleup.shadow") version "8.3.1"
    signing
    application
}

java {
    withJavadocJar()
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_11
}
tasks.withType<Javadoc> { isFailOnError = false }

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

project.setProperty("mainClassName","fr.inria.corese.gui.core.MainFrame")
tasks {
    shadowJar {
        manifest {
            attributes(
                "Main-Class" to "fr.inria.corese.gui.core.MainFrame"
            )
        }
        this.archiveClassifier = "app"
    }
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("fr.inria.corese:corese-rdf4j:5.0.0-SNAPSHOT")
    api("fr.inria.corese:corese-jena:5.0.0-SNAPSHOT")
    api("fr.inria.corese:corese-core:5.0.0-SNAPSHOT")
    api("org.graphstream:gs-core:1.2")
    api("org.apache.jena:jena-tdb:4.8.0")


    api("org.apache.jena:jena-arq:4.8.0")
    api("org.apache.jena:jena-core:4.8.0")
    api("org.graphstream:gs-ui:1.2")
    api("org.slf4j:slf4j-api:1.8.0-beta2")
    api("org.apache.logging.log4j:log4j-api:2.18.0")
    api("org.apache.logging.log4j:log4j-core:2.18.0")
    runtimeOnly("org.apache.logging.log4j:log4j-slf4j18-impl:2.18.0")
}

group = "fr.inria.corese"
version = "5.0.0-SNAPSHOT"
description = "corese-gui"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

extraJavaModuleInfo {
    failOnMissingModuleInfo.set(false)
    automaticModule("org.graphstream:gs-core", "gs.core")
    automaticModule("fr.com.hp.hpl.jena.rdf.arp:arp", "arp")
}