name: Publish Dev Pre-release
run-name: ${{ github.actor }} triggered pre-release on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to run workflow on'
        required: true
  push:
    branches:
      - develop

jobs:
  prerelease:
    name: Build and Publish Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build project
        run: ./gradlew build

      - name: Publish JAR to pre-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          tag: dev-prerelease
          name: "Development Pre-release"
          body: |
            🚧 This is the latest build from the `develop` branch.
            Not intended for production use.
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
